// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using TrainReservationApi.Data;

#nullable disable

namespace TrainReservationApi.Migrations
{
    [DbContext(typeof(ReservationDbContext))]
    partial class ReservationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("TrainReservationApi.entities.Rezervasyon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("KisiSayisi")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TrenAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("VagonAdi")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Rezervasyonlar");
                });

            modelBuilder.Entity("TrainReservationApi.entities.Tren", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Trenler");
                });

            modelBuilder.Entity("TrainReservationApi.entities.Vagon", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Ad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DoluKoltukAdet")
                        .HasColumnType("integer");

                    b.Property<int>("Kapasite")
                        .HasColumnType("integer");

                    b.Property<int?>("TrenId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TrenId");

                    b.ToTable("Vagonlar");
                });

            modelBuilder.Entity("TrainReservationApi.entities.Vagon", b =>
                {
                    b.HasOne("TrainReservationApi.entities.Tren", null)
                        .WithMany("Vagonlar")
                        .HasForeignKey("TrenId");
                });

            modelBuilder.Entity("TrainReservationApi.entities.Tren", b =>
                {
                    b.Navigation("Vagonlar");
                });
#pragma warning restore 612, 618
        }
    }
}
